spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zoodb
    username: zoo_user
    password: zeb98aP_5
    driver-class-name: org.postgresql.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp: 
          use_jdbc_metadata_defaults: false
